# Generated by Django 3.0.11 on 2024-03-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCompany', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('legal', models.CharField(blank=True, choices=[('1', 'Perorangan'), ('2', 'CV'), ('3', 'PT'), ('4', 'YAYASAN/FIRMA'), ('5', 'PT PERORANGAN')], max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.Company')),
            ],
        ),
    ]
