# Generated by Django 3.0.11 on 2024-03-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='legal',
            field=models.CharField(blank=True, choices=[('1', 'Supplier'), ('2', 'Customer'), ('3', 'Agen'), ('4', 'Distributor')], max_length=40, null=True),
        ),
    ]
